name: Trigger auto deployment for testing

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/testing-AutoDeployTrigger-60d6365b-f7cf-4d6f-8dfb-a9157add53d4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TESTING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTING_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/session3-api/DockerFile
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: testingcr2101.azurecr.io
          registryUsername: ${{ secrets.TESTING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTING_REGISTRY_PASSWORD }}
          containerAppName: testing
          resourceGroup: fb
          imageToBuild: testingcr2101.azurecr.io/testing:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


